# Swagger properties
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: list
    show-extensions: true
    show-common-extensions: true
    deep-linking: true
    default-model-rendering: model
    persist-authorization: true
